CREATE TABLE PROVEEDORES(

    ID_PROVEEDOR NUMBER PRIMARY KEY, 
	DNI VARCHAR2(8 ) NOT NULL UNIQUE, 
	NOMBRE VARCHAR2(50 ) NOT NULL , 
	DIRECCION VARCHAR2(50 ) NOT NULL , 
	TELEFONO VARCHAR2(9 ) NOT NULL , 
	ESTADO VARCHAR2(1 ) NOT NULL,
    --auditoria--
    AUD_IDPROVEEDOR NUMBER, 
	AUD_SESION VARCHAR2(20 ), 
	AUD_TIPO VARCHAR2(1 ), 
	AUD_IP NVARCHAR2(20), 
	AUD_NOMBRE_EQUIPO VARCHAR2(20), 
	AUD_FECHA DATE 
);

INSERT INTO proveedores(ID_PROVEEDOR,DNI,NOMBRE,DIRECCION,TELEFONO,ESTADO)
VALUES(SEQ_PROVEEDORE.nextval,'44037188','JUAN DE LA CRUZ MENDOZA','AV LOS ANGELES ATE NRO 20','3562291','1');



CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER PRIMARY KEY , 
	NOMBRE VARCHAR2(50 ) NOT NULL UNIQUE, 
	CANTIDAD NUMBER(4,0) NOT NULL , 
	PRECIO NUMBER(5,2) NOT NULL , 
	ESTADO VARCHAR2(1 BYTE) NOT NULL , 
	ID_USUARIO NUMBER, 
    CONSTRAINT FK_USUARIOS_PRODUCTOS FOREIGN KEY(ID_USUARIO)
    REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT "CK_CANTIDAD" CHECK (CANTIDAD>0) ENABLE, 
    CONSTRAINT "CK_PRECIO" CHECK (PRECIO>0) ENABLE, 
     --auditoria--
    AUD_IDPRODUSCTO NUMBER, 
	AUD_SESION VARCHAR2(20 ), 
	AUD_TIPO VARCHAR2(1 ), 
	AUD_IP NVARCHAR2(20), 
	AUD_NOMBRE_EQUIPO VARCHAR2(20), 
	AUD_FECHA DATE 
);